server:
  port: 12000

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    jdbcUrl: jdbc:postgresql://db:5432/mail-adn
    username: postgres
    password: kayser
    initialization-mode: always
    hikari:
      poolName: pool