jasypt:
   encryptor:
      password: ${jasyptpwd:secretkey}
      algorithm: PBEWithMD5AndDES

server:
   port: 8080
   servlet:
      context-path: /Dispatch
      session:
         timeout: 21600s
spring:
   profiles:
      active: dev