CREATE TABLE IF NOT EXISTS envio(
 id SERIAL,
 cedulaEmisor VARCHAR(12) NOT NULL,
 cedulaReceptor VARCHAR(12) NOT NULL,
 fecha DATE NULL,
 tipo VARCHAR(8) NOT NULL,
 peso DECIMAL(16,2) NULL,
 valor DECIMAL(16,2) NULL,
 PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS cliente(
 cedula VARCHAR(12) NOT NULL,
 nombre VARCHAR(30) NOT NULL,
 direccion VARCHAR(50) NOT NULL,
 telefono NUMERIC NULL,
 ciudad VARCHAR(20) NOT NULL,
 PRIMARY KEY(cedula)
);